addressbook/urls.py
# coding=utf-8
from django.conf.urls import patterns, url
from django.contrib.auth.views import login, logout

from addressbook import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<contact_id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<contact_id>\d+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<contact_id>\d+)/del/$', views.delete, name='delete'),
    url(r'^editpost/$', views.editpost, name='editpost'),
    url(r'^add/$', views.add, name='add'),
    url(r'^login/$',  login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^sync_ldap/$', views.ldap_sync, name='sync_ldap'),
)

itacc/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout


urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'itacc.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),
                       url(r'^addressbook/', include('addressbook.urls', namespace="addressbook")),
                       url(r'^cashbox/', include('cashbox.urls', namespace="cashbox")),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^login/$', login),
                       (r'^logout/$', logout),
                       )

addressbook/models.py
# coding=utf-8
from django.db import models


class Contact(models.Model):
    """ Контакты
    """
    login = models.CharField(max_length=40, unique=True)
    lastname = models.CharField(max_length=200)
    firstname = models.CharField(max_length=200)
    fathername = models.CharField(max_length=200, blank=True)
    company = models.CharField(max_length=200, blank=True)
    position = models.CharField(max_length=200, blank=True)
    department = models.CharField(max_length=200, blank=True)
    phone = models.CharField(max_length=200, blank=True)
    cellphone = models.CharField(max_length=200, blank=True)
    address = models.TextField(max_length=300, blank=True)
    email = models.EmailField(blank=True)
    photo = models.ImageField(blank=True)
    birthday = models.DateField(blank=True, null=True)
    active = models.BooleanField(default='False')

    def __unicode__(self):
        return "%s %s %s" % (self.lastname, self.firstname, self.fathername)


class Settings(models.Model):
    """ Настройки для синхронизации с AD.
    Должны быть значения: ldap_user, ldap_password, ldap_server, ldap_base
    """
    key = models.CharField(max_length=200)
    value = models.CharField(max_length=200)
    active = models.BooleanField(default=True)

    def __unicode__(self):
        return self.key

# нужно исправить на предупреждение, при двух одинаковых настройках, ну либо изменить тип хранения настроек
#    def save(self, *args, **kwargs):
#        if self.active==True:
#
#            raise  NameError('Only one active settings')
#        else:
#           super(Ldap_settings, self).save(*args, **kwargs)

addressbook/views.py
# coding=utf-8
import ldap
from datetime import datetime

from django.contrib.auth.decorators import user_passes_test
from django.db.models import Q
from django.shortcuts import get_object_or_404, render, redirect
from django.views.decorators.http import require_POST

from addressbook.models import Contact
from addressbook.models import Settings


def settings(item):
    """
    Получение настроек
    :param item: ключ настроек
    :return:

    """
    if item:
        value = Settings.objects.get(key=item).value
        if value:
            return value


def user_can_edit(user):
    """
    Проверка на возможность редактирования
    :param user:
    :return:

    """
    return user.is_authenticated() and user.has_perm("addressbook.Contact")


def search_contact(search_string):
    """
    Поиск контактов. С sqlite не работает поиск без учета регистра.
    Ссылка на документацию: https://docs.djangoproject.com/en/dev/ref/databases/#sqlite-string-matching
    :param search_string:
    :return:

    """
    return Contact.objects.filter(Q(lastname__icontains=search_string) |
                                  Q(firstname__icontains=search_string) | Q(fathername__icontains=search_string))


def index(request):
    """
    Список всех контактов
    :param request:
    :return:

    """
    user = request.user
    if request.POST:
        search_string = request.POST.get('search_string')
    else:
        search_string = ""
    if search_string == "":
        contacts_list = Contact.objects.order_by('lastname')
    else:
        contacts_list = search_contact(search_string).order_by('lastname')

    context = {'contacts_list': contacts_list, 'can_edit': user_can_edit(user),
               'search_string': search_string, 'current_day': datetime.now()}
    return render(request, 'addressbook/index.html', context)


def detail(request, contact_id):
    """
    Просмотр контакта
    :param request:
    :param contact_id:
    :return:

    """
    contact = get_object_or_404(Contact, pk=contact_id)
    return render(request, 'addressbook/detail.html', {'contact': contact})


@user_passes_test(user_can_edit, login_url="/login/")
def edit(request, contact_id):
    """
    Открытие формы редактирования контакта
    :param request:
    :param contact_id:
    :return:

    """
    contact = get_object_or_404(Contact, pk=contact_id)
    return render(request, 'addressbook/edit.html', {'contact': contact})


@user_passes_test(user_can_edit, login_url="/login/")
def delete(request, contact_id):
    """
    Удаление контакта
    :param request:
    :param contact_id:
    :return:

    """
    contact = get_object_or_404(Contact, pk=contact_id)
    contact.delete()
    return redirect('addressbook:index')


@user_passes_test(user_can_edit, login_url="/login/")
def add(request):
    """
    Добавление нового контакта

    :param request:
    :return:

    """
    return render(request, 'addressbook/edit.html')


@user_passes_test(user_can_edit, login_url="/login/")
@require_POST
def editpost(request):
    """
    Отправляет изменения контакта в базу

    :param request:
    :return:

    """
    contact_id = request.POST.get('id')
    if contact_id != "add_contact":
        selected_contact = get_object_or_404(Contact, pk=contact_id)
    else:
        selected_contact = Contact()
        selected_contact.pk = None

    selected_contact.lastname = request.POST.get('lastname')
    selected_contact.firstname = request.POST.get('firstname')
    selected_contact.fathername = request.POST.get('fathername')
    selected_contact.company = request.POST.get('company')
    selected_contact.position = request.POST.get('position')
    selected_contact.department = request.POST.get('department')
    selected_contact.phone = request.POST.get('phone')
    selected_contact.cellphone = request.POST.get('cellphone')
    selected_contact.address = request.POST.get('address')
    selected_contact.email = request.POST.get('email')
    if request.POST.get('birthday'):
        date_object = datetime.strptime(request.POST.get('birthday'), '%Y-%m-%d')
        selected_contact.birthday = date_object
    if request.POST.get('active'):
        selected_contact.active = True
    else:
        selected_contact.active = False
    selected_contact.save()
    return redirect('addressbook:index')


@user_passes_test(user_can_edit, login_url="/login/")
def ldap_sync(request):
    """Синхронизация с Active Directory"""
    l = ldap.initialize(settings("ldap_server"))
    try:
        l.protocol_version = ldap.VERSION3
        l.set_option(ldap.OPT_REFERRALS, 0)
        l.simple_bind_s(settings('ldap_user'), settings('ldap_password'))
        base = settings('ldap_base')
        criteria = "(&(mail=*)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(objectClass=user))"
        attributes = {'sn': 'lastname', 'givenName': 'firstname', 'mail': 'email',
                      'telephoneNumber': 'phone', 'mobile': 'cellphone',
                      'l': 'address', 'streetAddress': 'address', 'department': 'department',
                      'company': 'company', 'displayName': None, 'sAMAccountName': 'login', 'title': 'position'}
        result = l.search_s(base, ldap.SCOPE_SUBTREE, criteria, attributes.keys())
        results = [entry for dn, entry in result if isinstance(entry, dict)]

        for contact in results:
            contact_data = {}
            contact_login = ''
 
            for key in contact.keys():
                if key in ('l', 'streetAddress'):
                    contact_data['address'] = ", ".join([contact_data.get('address', ''), contact[key][0]])
                elif key == 'sAMAccountName':
                    contact_login = contact[key][0]
                elif key == 'displayName':
                    splitted_name = contact[key][0].split()
                    if len(splitted_name) == 3:
                        contact_data['lastname'], contact_data['firstname'], contact_data['fathername'] = splitted_name
                    elif len(splitted_name) == 2:
                        contact_data['lastname'], contact_data['firstname'] = splitted_name
                    elif len(splitted_name) == 1:
                        contact_data['lastname'] = contact[key][0]
                else:
                    contact_data[attributes[key]] = contact[key][0]

            try:
                new_contact, created = Contact.objects.update_or_create(login=contact_login, defaults=contact_data)
            except Exception:
                new_contact = ""
    finally:
        l.unbind()
    return redirect('addressbook:index')

addressbook/templates/addressbook/base.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head lang="ru">
    <style type="text/css">
        .center {
        top: 50%; /* Отступ в процентах от верхнего края окна */
        left: 50%; /* Отступ в процентах от левого края окна */
        width: 500px; /* Ширина блока */
        height: 450px; /* Высота блока */
        position: absolute; /* Абсолютное позиционирование блока */
        margin-top: -225px; /* Отрицательный отступ от верхнего края страницы, должен равняться половине высоты блока со
        знаком минус */
        margin-left: -225px; /* Отрицательный отступ от левого края страницы, должен равняться половине высоты блока со
        знаком минус */
        }
        tr:nth-child(2n) {
        background: #f0f0f0; /* Цвет фона */
        }
    </style>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

{% block auth %}
<div align="left">
    {% if user.is_authenticated %}
    Добрый день, {{ user.username }}!
    <a href="{% url 'addressbook:logout' %}?next={% url 'addressbook:index' %}">logout</a>
    {% else %}
    {% if form.errors %}
    <p class="error">Сожалеем, вы неправильно ввели логин или пароль</p>
    {% endif %}
    Добрый день, пожалуйста авторизуйтесь.
    <a href="{% url 'addressbook:login' %}?next={% url 'addressbook:index' %}">login</a>
    {% endif %}
</div>
{% endblock %}


{% block content %}
Добро пожаловать на сайте.
{% endblock content %}

</body>
</html>

addressbook/templates/addressbook/detail.html
{% extends "addressbook/base.html" %}

{% block content %}

{% if contact %}
<table align="center" border="0">
    <tr>
        <td align="right">
            <b>ФИО:</b>
        </td>
        <td>
            {{ contact.lastname }} {{ contact.firstname }} {{ contact.fathername}}
        </td>
    </tr>
    <tr>
        <td align="right">
            <b>Организация:</b>
        </td>
        <td>
            {{ contact.company }}
        </td>
    </tr>
    <tr>
        <td align="right">
            <b>Отдел:</b>
        </td>
        <td>
            {{ contact.department }}
        </td>
    </tr>
    <tr>
        <td align="right">
            <b>Должность:</b>
        </td>
        <td>
            {{ contact.position }}</p>

        </td>
    </tr>
    <tr>
        <td align="right">
            <b>Email:</b>
        </td>
        <td>
            <a href="mailto:{{ contact.email }}">{{ contact.email }}</a>
        </td>
    </tr>
    <tr>
        <td align="right">
            <b>Телефон:</b>
        </td>
        <td>
            {{ contact.phone }}
        </td>
    </tr>
    <tr>
        <td align="right">
            <b>Сотовый телефон:</b>
        </td>
        <td>
            {{ contact.cellphone }}
        </td>
    </tr>
    <tr>
        <td align="right">
            <b>Адрес:</b>
        </td>
        <td>
            {{ contact.address }}
        </td>
    </tr>
    <tr>
        <td align="right">
            <b>День рождения:</b>
        </td>
        <td>
            {% if contact.birthday %}
            {{ contact.birthday }}
            {% endif %}
        </td>
    </tr>
    <tr>
        <td align="right">
            {% if allowedit %}
            <a href="{% url 'addressbook:edit' contact.id %}"> Редактировать </a>
            {% endif %}
        </td>
        <td align="right">
            <a href=" {% url 'addressbook:index' %} ">Назад</a>
        </td>
    </tr>
</table>
{% endif %}
{% endblock content %}

addressbook/templates/addressbook/edit.html
{% extends "addressbook/base.html" %}

{% block content %}

{% if contact %}

{% if error_message %}<p xmlns="http://www.w3.org/1999/html"><strong>{{ error_message }}</strong></p>{% endif %}

<table align="center" border="0">
    <form action="{% url 'addressbook:editpost' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="id" id="id" value="{{ contact.id }}">

        <tr>
            <td align="right">
                <b>Фамилия:</b>
            </td>
            <td>
                <input type="text" name="lastname" id="lastname" value="{{ contact.lastname }}"
                       maxlength="{{ contact.lastname.max_length }}"/>
            </td>
        </tr>
        <tr>
            <td align="right">
                <b>Имя:</b>
            </td>
            <td>
                <input type="text" name="firstname" id="firstname" value="{{ contact.firstname }}" maxlength=200/>
            </td>
        </tr>
        <tr>
            <td align="right">
                <b>Отчество:</b>
            </td>
            <td>
                <input type="text" name="fathername" id="fathername" value="{{ contact.fathername }}" maxlength=200/>
            </td>
        </tr>
        <tr>
            <td align="right">
                <b>Организация:</b>
            </td>
            <td>
                <input type="text" name="company" id="company" value="{{ contact.company }}" maxlength=200/>
            </td>
        </tr>
        <tr>
            <td align="right">
                <b>Отдел:</b>
            </td>
            <td>
                <input type="text" name="department" id="department" value="{{ contact.department }}" maxlength=200/>
            </td>
        </tr>
        <tr>
            <td align="right">
                <b>Должность:</b>
            </td>
            <td>
                <input type="text" name="position" id="position" value="{{ contact.position }}" maxlength=200/>
            </td>
        </tr>
        <tr>
            <td align="right">
                <b>Email:</b>
            </td>
            <td>
                <input type="email" name="email" id="email" value="{{ contact.email }}"
                       maxlength="{{ contact.lastname.max_length }}"/>
            </td>
        </tr>
        <tr>
            <td align="right">
                <b>Телефон:</b>
            </td>
            <td>
                <input type="text" name="phone" id="phone" value="{{ contact.phone }}"
                       maxlength="{{ contact.lastname.max_length }}"/>
            </td>
        </tr>
        <tr>
            <td align="right">
                <b>Сотовый телефон:</b>
            </td>
            <td>
                <input type="text" name="cellphone" id="cellphone" value="{{ contact.cellphone }}"
                       maxlength="{{ contact.lastname.max_length }}"/>
            </td>
        </tr>
        <tr>
            <td align="right">
                <b>Адрес:</b>
            </td>
            <td>
                <input type="text" name="address" id="address" value="{{ contact.address }}"
                       maxlength="{{ contact.lastname.max_length }}"/>
            </td>
        </tr>
        <tr>
            <td align="right">
                <b>День рождения:</b>
            </td>
            <td>
                <input type="date" name="birthday" id="birthday" value="{{ contact.birthday|date:"Y-m-d" }}"/>
            </td>
        </tr>
        <tr>
            <td align="right">
                <b>Активен:</b>
            </td>
            <td>
                <input type="checkbox" name="active" id="active" value="{{ contact.active }}" {% if contact.active %}
                       checked {% endif %}/>
            </td>
        </tr>
        <tr>
            <td align="right">
                <input type="submit" value="Сохранить"/>
            </td>
            <td>
                <input type="reset"/>
            </td>

    </form>

    <form action="{% url 'addressbook:delete' contact.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="id" id="id" value="{{ contact.id }}">

        <td align="right">
            <input type="submit" value='Удалить'/>
        </td>
        <td align="right">
            <input type="button" value="Назад" onclick="history.back()">
        </td>
        </tr>
</table>
</form>
{% else %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'addressbook:editpost' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="id" id="id" value="add_contact">
    <table align="center" border="0">
        <tr>
            <td align="right">
                <b>Фамилия:</b>
            </td>
            <td>
                <input type="text" name="lastname" id="lastname" value="" maxlength="200"/>
            </td>
        </tr>
        <tr>
            <td align="right">
                <b>Имя:</b>
            </td>
            <td>
                <input type="text" name="firstname" id="firstname" value="" maxlength=200/>
            </td>
        </tr>
        <tr>
            <td align="right">
                <b>Отчество:</b>
            </td>
            <td>
                <input type="text" name="fathername" id="fathername" value="" maxlength=200/>
            </td>
        </tr>
        <tr>
            <td align="right">
                <b>Организация:</b>
            </td>
            <td>
                <input type="text" name="company" id="company" value="" maxlength=200/>
            </td>
        </tr>
        <tr>
            <td align="right">
                <b>Отдел:</b>
            </td>
            <td>
                <input type="text" name="department" id="department" value="" maxlength=200/>
            </td>
        </tr>
        <tr>
            <td align="right">
                <b>Должность:</b>
            </td>
            <td>
                <input type="text" name="position" id="position" value="" maxlength=200/>
            </td>
        </tr>
        <tr>
            <td align="right">
                <b>Email:</b>
            </td>
            <td>
                <input type="email" name="email" id="email" value="" maxlength="200"/>
            </td>
        </tr>
        <tr>
            <td align="right">
                <b>Телефон:</b>
            </td>
            <td>
                <input type="text" name="phone" id="phone" value="" maxlength=""/>
            </td>
        </tr>
        <tr>
            <td align="right">
                <b>Сотовый телефон:</b>
            </td>
            <td>
                <input type="text" name="cellphone" id="cellphone" value="" maxlength=""/>
            </td>
        </tr>
        <tr>
            <td align="right">
                <b>Адрес:</b>
            </td>
            <td>
                <input type="text" name="address" id="address" value="" maxlength=""/>
            </td>
        </tr>
        <tr>
            <td align="right">
                <b>День рождения:</b>
            </td>
            <td>
                <input type="date" name="birthday" id="birthday" value=""/>
            </td>
        </tr>
        <tr>
            <td align="right">
                <b>Активен:</b>
            </td>
            <td>
                <input type="checkbox" name="active" id="active" value=""/>
            </td>
        </tr>
        <tr>
            <td align="right">
                <input type="submit"/>
            </td>
            <td>
                <input type="reset"/>
            </td>
            <td align="right">
                <input type="button" value="Назад" onclick="history.back()">
            </td>
        </tr>
    </table>
</form>

{% endif %}
{% endblock content %}

addressbook/templates/addressbook/index.html
{% extends "addressbook/base.html" %}
{% load mathfilters %}
{% block content %}
<table border="0" align="center" cellspacing="5">

    <form action="{% url 'addressbook:index' %}" method="post" align="center">
        {% csrf_token %}
        <tr>
            <td>
                <input type="text" name="search_string" id="search_string" value="{{ search_string }}" maxlength="200"/>
            </td>
            <td>
                <input type="submit" value="Поиск"/>
            </td>

    </form>
    <form action="{% url 'addressbook:index' %}" method="post" align="center">
        {% csrf_token %}
        <td>
            <input type="hidden" name="search_string" id="search_string" value=""/>
            <input type="submit" value="Х"/>
        </td>
        </tr>
    </form>
    {% if contacts_list %}


    <table border="0" align="center" cellspacing="0">


        <tr>
            <th></th>
            <th><b>ФИО</b></th>
            <th><b>Email</b></th>
            <th><b>Телефон</b></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
        {% for contact in contacts_list %}
        <tr>
            <td>
                {% if contact.active or can_edit %}

                {% with birthday_month=contact.birthday|date:"m"|add:0 now_month=current_day|date:"m"|add:0 now_day=current_day|date:"d"|add:0 birthday_day=contact.birthday|date:"d"|add:0 now_day5=now_day|add:"5"%}

                {% if birthday_month == now_month and now_day|add:5 > birthday_day and now_day < birthday_day %}
                Дней до дня рождения: {{ birthday_day|sub:now_day }}
                {% endif %}
                {% if birthday_month == now_month and now_day == birthday_day %}
                Сегодня День рождения!
                {% endif %}
                {% endwith %}
            </td>
            <td><a href="{% url 'addressbook:detail' contact.id %}">{{ contact.lastname }} {{ contact.firstname }}
                {{ contact.fathername }}</a></td>
            <td><a href="mailto:{{ contact.email}}">{{ contact.email}}</a></td>
            <td>
                {% if contact.phone %}
                    {{ contact.phone }}
                {% endif %}
                {% if contact.phone and contact.cellphone %}
                    ,
                {% endif %}
                {% if contact.cellphone %}
                    {{ contact.cellphone }}
                {% endif %}
            </td>
            <td><a href="{% url 'addressbook:detail' contact.id %}"> Подробнее </a></td>
            {% if can_edit %}
            <td><a href="{% url 'addressbook:edit' contact.id %}"> Редактировать </a></td>
            <td><a href="{% url 'addressbook:delete' contact.id %}">Удалить</a></td>
            {% endif %}
        </tr>

        {% endif %}
        {% endfor %}


    </table>


    {% else %}
    <div><p>Адресная книга пуста.</p></div>
    {% endif %}
    {% if can_edit %}
    <table border="0" align="center" cellspacing="10">
        <tr>
            <td><a href="{% url 'addressbook:add' %}">Добавить</a></td>
            <td><a href="{% url 'addressbook:sync_ldap' %}">Синхронизировать</a></td>
        </tr>

    </table>
    {% endif %}

    {% endblock content %}